export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS'
export const API_CALL_ERROR = 'API_CALL_ERROR'

export const UNAUTHORIZED = 'UNAUTHORIZED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'